name: Main

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/shiftleft
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        GITHUB_REPO: "${{ github.repository }}"
        GITHUB_SHA: "${{ github.sha }}"
        GITHUB_REF: "${{ github.ref }}"
        SHIFTLEFT_ORG_ID: "${{ secrets.SHIFTLEFT_ORG_ID }}"
        SHIFTLEFT_ACCESS_TOKEN: "${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}"
        SHIFTLEFT_API_TOKEN: "${{ secrets.SHIFTLEFT_API_TOKEN }}"
