name: Main

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/foo
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        GITHUB_REPO: "${{ github.repository }}"
        GITHUB_SHA: "${{ github.sha }}"
        GITHUB_REF: "${{ github.ref }}"
